services:
  labelized_export.job.job_parameters.constraint_collection_provider.product_xlsx_export:
    class: '%pim_connector.job.job_parameters.constraint_collection_provider.product_xlsx_export.class%'
    arguments:
      - '@pim_connector.job.job_parameters.constraint_collection_provider.simple_xlsx_export'
      -
          - 'labelized_xlsx_product_export'
    tags:
      - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }