parameters:
  labelized_export.normalizer.standard.product.properties.class: Niji\AkeneoLabelizedExportBundle\Normalizer\Product\Standard\PropertiesNormalizer

services:
  labelized_export.normalizer.standard.product.properties:
    class: '%labelized_export.normalizer.standard.product.properties.class%'
    arguments:
      - '@pim_catalog.filter.chained'
      - '@pim_standard_format_serializer'
      - '@pimee_enrich.repository.attribute'
      - '@pim_catalog.normalizer.standard.attribute_option'
    tags:
      - { name: pim_serializer.normalizer, priority: 40 }