parameters:
  labelized_export.processor.normalization.product.class: Niji\AkeneoLabelizedExportBundle\Processor\ProductProcessor

services:
  labelized_export.processor.normalization.product:
    class: '%labelized_export.processor.normalization.product.class%'
    arguments:
    - '@labelized_export.normalizer.standard.product.properties'
    - '@pim_catalog.repository.channel'
    - '@pim_catalog.repository.attribute'
    - '@pim_connector.processor.bulk_media_fetcher'
    - '@pim_catalog.values_filler.product'
    - '@pim_connector.doctrine.cache_clearer'