services:
  labelized_export.step.xlsx_product.export:
    class: Akeneo\Tool\Component\Batch\Step\ItemStep
    arguments:
      - 'export'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      - '@pim_connector.reader.database.product'
      - '@labelized_export.processor.normalization.product'
      - '@labelized_export.writer.file.xlsx_product'
      - '%pim_job_product_batch_size%'